Keys:
  People:
    Theo: https://hooks.slack.com/services/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
    Steffen: https://hooks.slack.com/services/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
    Tyrrell: https://hooks.slack.com/services/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

  Channels:
    Factory: https://hooks.slack.com/services/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

Names:
  People:
    - Theo
    - Tyrrell
    - Steffen
  Channels: 
    - Factory

Emails: