#####################################################
#         Sample configuration file.                #
# Remove all comments starting with "#" before use. #
#                                                   #
#####################################################

Notifications:
  Names:
    People: # list people that will be detailed below
      - Adam
      - Eve
    Channels: # list channels that will be detailed below
      - Garden
  People: # people nest under people
    Adam: # name the dictionary the name of the person to be detailed
      Name: Adam
      Key: None # slack webhooks key for adam
      email: Adam@eden.com
    Eve:
      Name: Eve
      Key: None # slack webhooks key for eve
      email: eve@eden.com
  Channels: # channels nest under channels
    Garden:
      Name: Garden
      Key: None # slack webhooks key for garden
      email: None

Parameters:
  display_update: [0,30] # interval to update the display
  data_log_interval: [0,15,30,45] # interval to log the data
  datasheet_prefix: sample_filename # first part of the google sheet name
  datasheet_appendix: '%Y%m%d_%h%m' # last part of the google sheet name
  Tunits: 'C' # temperature units 
  flowUnits: 'L/s'  # flow units 
  upperT_limit: 90 # upper sensor temperature limit to trigger alarm
  lowerT_limit: 120 # lower sensor temperature limit to trigger alarm, set high if you want the error to trigger on the upper temperature sensor.
  flow_limit: 10 # flow limit to trigger alarm
  alert_limit: 30 # number of minutes to wait before sending another alarm
  shareData: ['Theo'] # people, detailed above, to share data with
  fontsize: 18 # display font size.
  googleAPI_key: 'path_to_credentials_json_file' # path to google sheets API 
  alertPeople: ['Theo'] # names of people, detailed above, to alert if an alert is triggered. Can be people or channels.
  statusUpdate: ['Theo'] # names of people, detailed above, to notify when a distillation starts. Can be people or channels.
  datasheetCols: ['datetime','upperT','lowerT','flow','voc','eco2'] # columns to create in the google sheet
  time_fmt: '%Y-%m-%d %H:%M:%S' # time format to use with datalogging
  node_name: kumquat # name of the sensor node
  logPath: './logs' # path to store log files
  logName: 'distillation' # first part of the logfile name, the second part will be the datasheet_appendix variable